### ISSUE TITLE
array_key_exists() warning

### ISSUE THREAD

**Issue by Izacktly** [Jako/AjaxUpload#7] opened 2016-08-07 16:40 UTC
Hello,

I'm using the following call;
[[!AjaxUpload?
&uid=`image`
&allowedExtensions=`jpg,jpeg,png,gif`
&thumbX=`75`
&thumbY=`75`
&maxFiles=`5`
&maxFilesizeMb=`1`
]]

I'm using Modx version 2.5.0 & php version 5.6.20.  I saw the last comment from nick2687, but my jquery was already included at the bottom.
Since the latest upgrade of ajaxUpload,, the modx error log shows alot of the following errors;

[2016-08-07 11:13:33] (ERROR @ /paas/c1879/www/core/components/ajaxupload/model/ajaxupload/ajaxupload.class.php : 108) PHP warning: array_key_exists() expects parameter 2 to be array, null given.

**Comment by nick2687** [comment] 2016-08-07 16:43
Turns out what I mentioned was not the fix... It's happening very sporadic for me. Sometimes it loads fine, others it returns this same error.

**Comment by Izacktly** [comment] 2016-08-07 16:45
Yes agreed.  The functionality works fine for me.  Its just my error log is going crazy lol

**Comment by Jako** [comment] 2016-08-08 08:08
Duplicate of #6

**Closed by Jako** 2016-08-08 08:08 UTC
